# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]

members = ["leetcode", "tokio_axum"]

# command for initilizing the member :: cargo new --lib <member_name>
